### ISSUE TITLE
Permission to reuse some of the slides?

### ISSUE THREAD

**Issue by pmbanka** [russcam/fsharp-akka-talk#2]
Hi,

I'm currently involved in a project using F# + Akka and I was asked to deliver some internal presentation about the topic for my colleagues. While searching for some materials I found your presentation, which covers exactly what I wanted to talk about - and in a much more organized way that I would ever come up with! That's why I would like to ask you for a permission to use some of your slides and code samples in my presentation. Of course I would include a proper attribution and links to your work.

Thanks! :)

**Comment by russcam** [comment]
I've only just seen this @pmbanka, apologies 😢 Please feel free to use and attribute 👍

**Comment by pmbanka** [comment]
No problem! I ended up going for it because it is better to ask for forgiveness than permission ;) Many thanks for creating such great presentation!
